WiP: Add proto files
hb-voles/csgo-prs pull request #4
Opened 2018-03-10 08:14 UTC by celestian

label: architecture

https://stackoverflow.com/questions/13939904/how-to-use-protocol-buffers-with-autoconf-automake

2018-03-10 10:03 UTC, stlaz requested changes

2018-03-10 10:03 UTC, stlaz commented on src/demofile.cc
> +}
PLease add an EOL.

2018-03-10 10:03 UTC, stlaz commented on .gitignore
> +*.pb.h
Please add an EOL.

2018-03-10 10:03 UTC, stlaz commented on src/cstrike15_gcmessages.proto
> +import "src/steammessages.proto";
Let's have a subfolder for the .proto files, e.g. `src/protobuffs`

2018-03-11 03:13 UTC, celestian commented
Addressed and it works now :-)

2018-03-11 08:11 UTC, merged